-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 23:43:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vacinaeu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vacinaeu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vacinaeu` DEFAULT CHARACTER SET utf8 ;
USE `vacinaeu` ;

-- -----------------------------------------------------
-- Table `vacinaeu`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`empresas` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `emp_nome` VARCHAR(45) NOT NULL,
  `emp_cnpj` VARCHAR(14) NOT NULL,
  `emp_email` VARCHAR(45) NOT NULL,
  `emp_senha` VARCHAR(250) NOT NULL,
  `emp_status` ENUM("Ativo", "Inativo") NOT NULL DEFAULT 'Ativo',
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacinaeu`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`lotes` (
  `lot_id` INT NOT NULL AUTO_INCREMENT,
  `lot_nome` VARCHAR(45) NOT NULL,
  `lot_qtdDisponivel` INT NOT NULL,
  `lot_status` ENUM("Ativo", "Inativo") NOT NULL DEFAULT 'Ativo',
  `emp_id` INT NOT NULL,
  PRIMARY KEY (`lot_id`),
  INDEX `fk_lotes_empresas_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_lotes_empresas`
    FOREIGN KEY (`emp_id`)
    REFERENCES `vacinaeu`.`empresas` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacinaeu`.`locais_vacinacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`locais_vacinacao` (
  `loc_id` INT NOT NULL AUTO_INCREMENT,
  `loc_estado` VARCHAR(2) NOT NULL,
  `loc_status` ENUM("Ativo", "Inativo") NOT NULL DEFAULT 'Ativo',
  `emp_id` INT NOT NULL,
  PRIMARY KEY (`loc_id`),
  INDEX `fk_locais_vacinacao_empresas1_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_locais_vacinacao_empresas1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `vacinaeu`.`empresas` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacinaeu`.`vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`vacina` (
  `vac_id` INT NOT NULL AUTO_INCREMENT,
  `vac_nome` VARCHAR(45) NOT NULL,
  `vac_qtdDoses` VARCHAR(45) NOT NULL,
  `vac_doseAtual` VARCHAR(45) NOT NULL,
  `vac_datavacinacao` DATE NOT NULL,
  `vac_estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`vac_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacinaeu`.`pessoas_imunizadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`pessoas_imunizadas` (
  `pes_id` INT NOT NULL AUTO_INCREMENT,
  `pes_nome` VARCHAR(45) NOT NULL,
  `pes_idade` INT NOT NULL,
  `pes_datanascimento` DATE NOT NULL,
  `pes_cpf` VARCHAR(45) NOT NULL,
  `pes_sexo` ENUM('M', 'F') NOT NULL,
  `pes_status` ENUM("Ativo", "Inativo") NOT NULL DEFAULT 'Ativo',
  `emp_id` INT NOT NULL,
  `vac_id` INT NOT NULL,
  PRIMARY KEY (`pes_id`),
  INDEX `fk_pessoas_imunizadas_empresas1_idx` (`emp_id` ASC) VISIBLE,
  INDEX `fk_pessoas_imunizadas_vacina1_idx` (`vac_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_imunizadas_empresas1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `vacinaeu`.`empresas` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_imunizadas_vacina1`
    FOREIGN KEY (`vac_id`)
    REFERENCES `vacinaeu`.`vacina` (`vac_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacinaeu`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacinaeu`.`endereco` (
  `end_id` INT NOT NULL AUTO_INCREMENT,
  `end_endereco` VARCHAR(45) NOT NULL,
  `end_numero` INT NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_estado` VARCHAR(2) NOT NULL,
  `pes_id` INT NOT NULL,
  PRIMARY KEY (`end_id`),
  INDEX `fk_endereco_pessoas_imunizadas1_idx` (`pes_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_pessoas_imunizadas1`
    FOREIGN KEY (`pes_id`)
    REFERENCES `vacinaeu`.`pessoas_imunizadas` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
